"""create posts table and post_count check

Revision ID: 0a806283fdf1
Revises: b466e5a635b7
Create Date: 2026-09-13 16:14:18.863182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a806283fdf1'
down_revision: Union[str, Sequence[str], None] = 'b466e5a635b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('board_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_author', 'posts', ['author_id'], unique=False)
    op.create_index('ix_posts_board_id', 'posts', ['board_id', sa.literal_column('id DESC')], unique=False)
    # ### end Alembic commands ###

    # autogenerate 는 CheckConstraint 를 감지하지 않으므로 직접 작성한다.
    # 카운트가 음수가 되면 로직 버그이므로 조용히 깎지 않고 에러로 드러낸다.
    op.create_check_constraint('ck_boards_post_count_non_negative', 'boards', 'post_count >= 0')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_board_id', table_name='posts')
    op.drop_constraint('ck_boards_post_count_non_negative', 'boards', type_='check')
    op.drop_index('ix_posts_author', table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
