"""create boards table

Revision ID: b466e5a635b7
Revises: 652861b87262
Create Date: 2026-09-13 15:30:53.460442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b466e5a635b7'
down_revision: Union[str, Sequence[str], None] = '652861b87262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_boards_private_owner_count', 'boards', [sa.literal_column('owner_id, post_count DESC, id DESC')], unique=False, postgresql_where=sa.text('NOT is_public'))
    op.create_index('ix_boards_public_count', 'boards', [sa.literal_column('post_count DESC, id DESC')], unique=False, postgresql_where=sa.text('is_public'))
    op.create_index('uq_boards_name', 'boards', [sa.literal_column('lower(name)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_boards_name', table_name='boards')
    op.drop_index('ix_boards_public_count', table_name='boards', postgresql_where=sa.text('is_public'))
    op.drop_index('ix_boards_private_owner_count', table_name='boards', postgresql_where=sa.text('NOT is_public'))
    op.drop_table('boards')
    # ### end Alembic commands ###
